//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PicannolEntities : DbContext
    {
        public PicannolEntities()
            : base("name=PicannolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Log> Logs { get; set; }
        public DbSet<tblAudit> tblAudits { get; set; }
        public DbSet<tblBusiness> tblBusinesses { get; set; }
        public DbSet<tblChallan> tblChallans { get; set; }
        public DbSet<tblCreditNote> tblCreditNotes { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblDebitNote> tblDebitNotes { get; set; }
        public DbSet<tblDetailedExpens> tblDetailedExpenses { get; set; }
        public DbSet<tblDispatchDetail> tblDispatchDetails { get; set; }
        public DbSet<tblEInvoice> tblEInvoices { get; set; }
        public DbSet<tblInvoice> tblInvoices { get; set; }
        public DbSet<tblOrder> tblOrders { get; set; }
        public DbSet<tblOrderPart> tblOrderParts { get; set; }
        public DbSet<tblOrderPayment> tblOrderPayments { get; set; }
        public DbSet<tblPart> tblParts { get; set; }
        public DbSet<tblPartHistory> tblPartHistories { get; set; }
        public DbSet<tblPartLoan> tblPartLoans { get; set; }
        public DbSet<tblPartType> tblPartTypes { get; set; }
        public DbSet<tblProformaInvoice> tblProformaInvoices { get; set; }
        public DbSet<tblProvisionalBill> tblProvisionalBills { get; set; }
        public DbSet<tblPurchase> tblPurchases { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblServiceDay> tblServiceDays { get; set; }
        public DbSet<tblServiceRequest> tblServiceRequests { get; set; }
        public DbSet<tblSubCustomer> tblSubCustomers { get; set; }
        public DbSet<tblTimeSheet> tblTimeSheets { get; set; }
        public DbSet<tblTimeSheetDetail> tblTimeSheetDetails { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblWorkOrderImage> tblWorkOrderImages { get; set; }
        public DbSet<tblWorkOrder> tblWorkOrders { get; set; }
        public DbSet<tblZone> tblZones { get; set; }
        public DbSet<tblCustomerContact> tblCustomerContacts { get; set; }
        public DbSet<tblGSTState> tblGSTStates { get; set; }
        public DbSet<tblServiceCallType> tblServiceCallTypes { get; set; }
    
        public virtual int usp_UpdatetblPart(Nullable<int> partId, string partName, string partNumber, string serialNumber, Nullable<int> newStock, Nullable<decimal> price, string remarks, Nullable<int> userId, Nullable<System.DateTime> purchaseDate)
        {
            var partIdParameter = partId.HasValue ?
                new ObjectParameter("PartId", partId) :
                new ObjectParameter("PartId", typeof(int));
    
            var partNameParameter = partName != null ?
                new ObjectParameter("PartName", partName) :
                new ObjectParameter("PartName", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var serialNumberParameter = serialNumber != null ?
                new ObjectParameter("SerialNumber", serialNumber) :
                new ObjectParameter("SerialNumber", typeof(string));
    
            var newStockParameter = newStock.HasValue ?
                new ObjectParameter("NewStock", newStock) :
                new ObjectParameter("NewStock", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var purchaseDateParameter = purchaseDate.HasValue ?
                new ObjectParameter("PurchaseDate", purchaseDate) :
                new ObjectParameter("PurchaseDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdatetblPart", partIdParameter, partNameParameter, partNumberParameter, serialNumberParameter, newStockParameter, priceParameter, remarksParameter, userIdParameter, purchaseDateParameter);
        }
    }
}
