//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PicannolEntities : DbContext
    {
        public PicannolEntities()
            : base("name=PicannolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Log> Logs { get; set; }
        public DbSet<tblAudit> tblAudits { get; set; }
        public DbSet<tblBusiness> tblBusinesses { get; set; }
        public DbSet<tblChallan> tblChallans { get; set; }
        public DbSet<tblCreditNote> tblCreditNotes { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblDetailedExpens> tblDetailedExpenses { get; set; }
        public DbSet<tblDispatchDetail> tblDispatchDetails { get; set; }
        public DbSet<tblEInvoice> tblEInvoices { get; set; }
        public DbSet<tblInvoice> tblInvoices { get; set; }
        public DbSet<tblOrder> tblOrders { get; set; }
        public DbSet<tblOrderPart> tblOrderParts { get; set; }
        public DbSet<tblOrderPayment> tblOrderPayments { get; set; }
        public DbSet<tblPart> tblParts { get; set; }
        public DbSet<tblPartLoan> tblPartLoans { get; set; }
        public DbSet<tblPartType> tblPartTypes { get; set; }
        public DbSet<tblProformaInvoice> tblProformaInvoices { get; set; }
        public DbSet<tblProvisionalBill> tblProvisionalBills { get; set; }
        public DbSet<tblPurchase> tblPurchases { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblServiceDay> tblServiceDays { get; set; }
        public DbSet<tblServiceRequest> tblServiceRequests { get; set; }
        public DbSet<tblSubCustomer> tblSubCustomers { get; set; }
        public DbSet<tblTimeSheet> tblTimeSheets { get; set; }
        public DbSet<tblTimeSheetDetail> tblTimeSheetDetails { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblWorkOrderImage> tblWorkOrderImages { get; set; }
        public DbSet<tblWorkOrder> tblWorkOrders { get; set; }
        public DbSet<tblCustomerContact> tblCustomerContacts { get; set; }
        public DbSet<tblGSTState> tblGSTStates { get; set; }
        public DbSet<tblServiceCallType> tblServiceCallTypes { get; set; }
    }
}
