//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblChallans = new HashSet<tblChallan>();
            this.tblSubCustomers = new HashSet<tblSubCustomer>();
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PIN { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Mobile { get; set; }
        public string ContactPerson { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public int BusinessId { get; set; }
        public Nullable<decimal> BigPacking { get; set; }
        public Nullable<decimal> BigForwarding { get; set; }
        public Nullable<decimal> SmallPacking { get; set; }
        public Nullable<decimal> SmallForwarding { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingDistrict { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPIN { get; set; }
        public string StateCode { get; set; }
        public Nullable<decimal> RepairCharges { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Delind { get; set; }
        public string Zone { get; set; }
        public string ShippingStateCode { get; set; }

        public virtual ICollection<tblChallan> tblChallans { get; set; }
        public virtual ICollection<tblSubCustomer> tblSubCustomers { get; set; }
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
