//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerContact
    {
        public int CustomerContactId { get; set; }
        public int CustomerId { get; set; }
        public string Department { get; set; }
        public string ContactPersonName { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public bool DelInd { get; set; }
    }
}
