//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChallan
    {
        public int ChallanId { get; set; }
        public string ChallanNumber { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ChallanType { get; set; }
        public int CustomerId { get; set; }
        public string Remarks { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
