//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditNote
    {
        public int CreditNoteId { get; set; }
        public System.Guid OrderGuid { get; set; }
        public string CreditNoteNo { get; set; }
        public System.DateTime CreditNoteDate { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal TaxableAmount { get; set; }
        public int CustomerId { get; set; }
        public decimal TaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool DelInd { get; set; }
        public string CreditNoteFileName { get; set; }
        public Nullable<int> Createdby { get; set; }
        public int ProvisionalBillId { get; set; }
        public decimal ComponentCost { get; set; }
        public decimal LabourCost { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal Fare { get; set; }
        public decimal PocketExpeses { get; set; }
        public decimal BoardingCharges { get; set; }
        public decimal BoardingDays { get; set; }
        public decimal ServiceDays { get; set; }
        public decimal ConveyanceExpenses { get; set; }
        public decimal ConveyanceExpenseDays { get; set; }
        public decimal PocketExpenseDays { get; set; }
        public decimal OvertimeHours { get; set; }
        public decimal OvertimeCharges { get; set; }
        public decimal OvertimeAmount { get; set; }
        public bool CRNCreated { get; set; }
        public bool Cancelled { get; set; }
        public int CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public int SubCustomerId { get; set; }
        public decimal PackagingForwarding { get; set; }
    }
}
