//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDispatchDetail
    {
        public int DispatchId { get; set; }
        public long TrackingNumber { get; set; }
        public System.Guid OrderGUID { get; set; }
        public string InvoiceNo { get; set; }
        public string DocketNo { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string DispatchDetails { get; set; }
        public string ImageName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool DelInd { get; set; }
    }
}
