//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetailedExpens
    {
        public int DetailedExpensesId { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public Nullable<int> ProvisionalBillId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Type { get; set; }
        public string ExpenseFrom { get; set; }
        public string ExpenseTo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool DelInd { get; set; }
    }
}
