//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDebitNote
    {
        public int DebitNoteId { get; set; }
        public System.Guid OrderGuid { get; set; }
        public string DebitNoteNo { get; set; }
        public string CreditNoteNo { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime DebitNoteDate { get; set; }
        public string DebitNoteFileName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public decimal Amount { get; set; }
        public int CustomerId { get; set; }
        public int ProvisionalBillId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool DelInd { get; set; }
        public int SubCustomerId { get; set; }
    }
}
