//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEInvoice
    {
        public int EInvoiceId { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string IRN { get; set; }
        public string QRCodeBase64 { get; set; }
        public string QRCode { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string IRNGeneratedBy { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public bool DelInd { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public int ProvisionalBillId { get; set; }
    }
}
