//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSTState
    {
        public int GSTStateId { get; set; }
        public string StateName { get; set; }
        public string StateInitials { get; set; }
        public string StateCode { get; set; }
        public string StateType { get; set; }
        public bool DelInd { get; set; }
    }
}
