//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid OrderGuid { get; set; }
        public decimal Amount { get; set; }
        public int CustomerId { get; set; }
        public int Status { get; set; }
        public bool DelInd { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string InvoiceFileName { get; set; }
        public Nullable<System.DateTime> SendOnDate { get; set; }
        public string SendTo { get; set; }
        public Nullable<int> ProvisionalBillId { get; set; }
        public Nullable<int> SubCustomerId { get; set; }
        public Nullable<decimal> Packing { get; set; }
        public Nullable<decimal> Forwading { get; set; }
        public Nullable<decimal> RepairCharge { get; set; }
        public Nullable<decimal> ComponentCost { get; set; }
        public Nullable<int> GeneratedByUserId { get; set; }
        public string BillingAddress { get; set; }
        public string StateCode { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingStateCode { get; set; }

    }
}
