//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPayment
    {
        public int OrderPaymentId { get; set; }
        public System.Guid OrderGUID { get; set; }
        public System.Guid PaymentGUID { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string PaymentType { get; set; }
        public string PaymentDetails { get; set; }
        public System.DateTime LastModified { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public int CustomerId { get; set; }
        public bool DelInd { get; set; }
        public bool Paid { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public int ProvisionalBillId { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public string Status { get; set; }
        public int UserId { get; set; }
        public decimal BalanceAmount { get; set; }
    }
}
