//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPart
    {
        public int OrderPartId { get; set; }
        public System.Guid OrderGUID { get; set; }
        public int PartId { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public bool DelInd { get; set; }
        public int UserId { get; set; }
        public int Deletedby { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
