//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public tblOrder()
        {
            this.tblOrderParts = new HashSet<tblOrderPart>();
        }
    
        public System.Guid OrderGUID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long TrackingNumber { get; set; }
        public int CustomerId { get; set; }
        public int ChallanId { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string RepairType { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> DelInd { get; set; }
        public int PartId { get; set; }
        public Nullable<decimal> RepairTime { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackingType { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<bool> Dispatched { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<bool> ExemptLabourCost { get; set; }
        public Nullable<bool> ExemptComponentCost { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblPart tblPart { get; set; }
        public virtual ICollection<tblOrderPart> tblOrderParts { get; set; }
    }
}
