//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProformaInvoice
    {
        public int ProformaInvoiceId { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid OrderGuid { get; set; }
        public decimal Amount { get; set; }
        public int CustomerId { get; set; }
        public int Status { get; set; }
        public bool DelInd { get; set; }
        public Nullable<System.DateTime> ProformaInvoiceDate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public decimal Packing { get; set; }
        public decimal Forwading { get; set; }
        public decimal RepairCharge { get; set; }
        public decimal ComponentCost { get; set; }
        public string PackingType { get; set; }
        public string BillingAddress { get; set; }
        public string StateCode { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingStateCode { get; set; }
    }
}
