//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentRecord
    {
        public int PaymentId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<decimal> AmountPayble { get; set; }
        public bool DelInd { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal TDS { get; set; }
        public string PaymentMode { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public string ProformaInvoicenumber { get; set; }
    }
}
