//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPart
    {
        public tblPart()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int PartId { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string SerialNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<int> Stock { get; set; }
        public int PartTypeId { get; set; }
        public Nullable<bool> DelInd { get; set; }
        public Nullable<int> OpeningStock { get; set; }
        public Nullable<System.DateTime> OpeningStockDate { get; set; }
        public string Location { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual tblPartType tblPartType { get; set; }
    }
}
