//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        public int PartId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> DelInd { get; set; }
        public int PurchaseId { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
