//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartHistory
    {
        public int PartHistoryId { get; set; }
        public int PartId { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public string SerialNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<int> Stock { get; set; }
        public int PartTypeId { get; set; }
        public Nullable<bool> DelInd { get; set; }
        public Nullable<int> OpeningStock { get; set; }
        public Nullable<System.DateTime> OpeningStockDate { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
