//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartLoan
    {
        public System.Guid OrderGUID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Returned { get; set; }
        public Nullable<int> ReturnedBy { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Remarks { get; set; }
        public bool DelInd { get; set; }
        public int LoanId { get; set; }
    }
}
