//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceRequest
    {
        public int ServiceRequestId { get; set; }
        public int CustomerId { get; set; }
        public string MachineName { get; set; }
        public int UserId { get; set; }
        public string CallType { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int ServiceCharge { get; set; }
        public int Fare { get; set; }
        public int PocketExpenses { get; set; }
        public int BoardingCharges { get; set; }
        public int BoardingDays { get; set; }
        public int ConveyanceExpenses { get; set; }
        public int OtherCharges { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool DelInd { get; set; }
        public int GST { get; set; }
        public int FinalAmount { get; set; }
        public int ServiceDays { get; set; }
        public string AuthorizedBy { get; set; }
        public string Designation { get; set; }
        public string EmailId { get; set; }
        public string ImageId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<int> ConveyanceExpenseDays { get; set; }
        public Nullable<int> PocketExpenseDays { get; set; }
        public Nullable<bool> Authorized { get; set; }
        public Nullable<System.DateTime> AuthorizedOn { get; set; }
        public string ServiceBillNo { get; set; }
        public Nullable<int> OvertimeHours { get; set; }
        public Nullable<int> OvertimeCharges { get; set; }
        public Nullable<int> OvertimeAmount { get; set; }
        public string UserSignatureId { get; set; }
    }
}
