//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceCallType
    {
        public int CallTypeId { get; set; }
        public string CallTypeNumber { get; set; }
        public string Description { get; set; }
        public bool ServiceCharges { get; set; }
        public bool DelInd { get; set; }
    }
}
