//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCustomer
    {
        public tblSubCustomer()
        {
            this.tblProvisionalBills = new HashSet<tblProvisionalBill>();
        }
    
        public int SubCustomerId { get; set; }
        public string SubCustomerName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string PIN { get; set; }
        public string ConatctPerson { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string GSTIN { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> DelInd { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual ICollection<tblProvisionalBill> tblProvisionalBills { get; set; }
    }
}
