//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeSheet
    {
        public int TimeSheetId { get; set; }
        public string TimeSheetNo { get; set; }
        public int WorkOrderId { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Remarks { get; set; }
        public bool DelInd { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedOn { get; set; }
        public bool Authorized { get; set; }
        public string ImageId { get; set; }
        public string TimeSheetFileName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string EmailId { get; set; }
        public string Designation { get; set; }
        public string UserSignatureId { get; set; }
        public Nullable<bool> FinalSubmit { get; set; }
        public Nullable<int> ProvisionalBillId { get; set; }
    }
}
