//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeSheetDetail
    {
        public int TimeSheetDetailId { get; set; }
        public int TimeSheetId { get; set; }
        public string WorkDate { get; set; }
        public string TotalHours { get; set; }
        public string Description { get; set; }
        public bool DelInd { get; set; }
        public Nullable<int> WeekNo { get; set; }
    }
}
