//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public string NotificationId { get; set; }
        public Nullable<bool> DelInd { get; set; }
        public string OTP { get; set; }
        public Nullable<bool> OtpVarify { get; set; }
        public string MobileNo { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
