//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picanol.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrder
    {
        public tblWorkOrder()
        {
            this.tblWorkOrderImages = new HashSet<tblWorkOrderImage>();
        }
    
        public int WorkOrderId { get; set; }
        public System.Guid WorkOrderGUID { get; set; }
        public string WorkOrderNo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public int CustomerId { get; set; }
        public string WorkOrderType { get; set; }
        public string ContractNumber { get; set; }
        public string ContactPerson { get; set; }
        public string EmailId { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Conditions { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public bool DelInd { get; set; }
        public string CallType { get; set; }
    
        public virtual ICollection<tblWorkOrderImage> tblWorkOrderImages { get; set; }
    }
}
